---
- name: Prerequisite for OpenStack
  hosts: localhost
  become: true
  connection: local
  tasks:
    - name: Install chrony
      apt:
        name: chrony
        state: present
        update_cache: true
        
    - name: Start chrony service
      service:
        name: chrony
        state: started
        enabled: true
        
    - name: Configure Chrony
      template:
        src: chrony.conf.j2
        dest: /etc/chrony/chrony.conf
        owner: root
        group: root
        mode: 0644
      notify: restart chrony
      
    - name: Open UDP port 123
      ufw:
        rule: allow
        port: 123
        proto: udp
        state: enabled
       
  handlers:
    - name: restart chrony
      service:
        name: chrony
        state: restarted
