---
# tasks file for localhost
- name: Install chrony
  apt:
   name: chrony
   state: latest
   update_cache: yes

- name: Start chrony
  service:
    name: chrony
    state: started
    enabled: yes
